### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by Pikku-a** [Inochi2D/inochi2d-c#9]
I have never used d language or dub, so sorry if there are dumb mistakes here.

I get this error when trying to build this:

```
Failed to invoke the compiler ldc to determine the build platform: /bin/sh: 1: ldc: not found

make: *** [Makefile:2: out/libinochi2d-c.so] Error 2
```

So in the makefile I changed ldc to ldc2. Then I get this error:
```
source/binding/render.d(9,1): Error: module `binding` from file source/binding/render.d conflicts with package name binding
ldc2 failed with exit code 1.
```

I tried changing "source" folder name to "source_" and added this to dub.selections.json:

`"sourcePath": ["source_"]`

Then I don't get that error anymore and the building seems to continue a little further. Then I get this error:

`fatal: not a git repository (or any of the parent directories): .git`

Also it said:

`Selected package inochi2d 0.7.2 does not match the dependency specification ~>0.9.0 in package inochi2d-c. Need to "dub upgrade"?`

But that warning disappears if in dub.sdl I change
`
dependency "inochi2d" version="~>0.9.0"`
to
`dependency "inochi2d" version="~>0.7.2"`

The whole compile log at this point:

```
make
dub build --force --compiler=ldc2 --config=yesgl
Configuration 'yesgl' of package inochi2d-c contains no source files. Please add {"targetType": "none"} to its package description to avoid building it.
Performing "debug" build using ldc2 for x86_64.
bindbc-loader 1.0.3: building configuration "noBC"...
bindbc-opengl 1.0.5: building configuration "dynamic"...
mir-core 1.5.5: building configuration "library"...
mir-algorithm 3.20.1: building configuration "default"...
fghj 1.0.1: building configuration "library"...
imagefmt 2.1.2: building configuration "library"...
inmath 1.0.5: building configuration "library"...
inochi2d 0.7.2: building configuration "full"...
Running pre-build commands...
Building package gitver in /home/myusername/.dub/packages/gitver-1.6.1/gitver/
Performing "debug" build using /usr/bin/ldc2 for x86_64.
semver 0.3.4: target for configuration "library" is up to date.
gitver 1.6.1: target for configuration "application" is up to date.
To force a rebuild of up-to-date targets, run again with --force.
Running ../../gitver-1.6.1/gitver/out/gitver --prefix IN --file source/inochi2d/ver.d --mod inochi2d.ver --appname Inochi2D
fatal: not a git repository (or any of the parent directories): .git
```

I'm probably doing something wrong, but what is it?

**Comment by LunaTheFoxgirl** [comment]
Inochi2D is currently under a heavy rewrite, as such building Inochi2D C is very cumbersome and requires cloning dependencies from git and adding them to the local dub database to downgrade things so that it will work.

I recommend waiting till Inochi2D 0.9 releases which will feature a new bring your own renderer design.

**Comment by Pikku-a** [comment]
Okay, I will wait for that.
